<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('locations')->insert(
            array(
                array('sub' => 'Ainabkoi', 'sub_code' => 'KE027144', 'county' => 'Uasin Gishu', 'county_code' => 'KE027'),
                array('sub' => 'Ainamoi', 'sub_code' => 'KE035190', 'county' => 'Kericho', 'county_code' => 'KE035'),
                array('sub' => 'Aldai', 'sub_code' => 'KE029152', 'county' => 'Nandi', 'county_code' => 'KE029'),
                array('sub' => 'Alego Usonga', 'sub_code' => 'KE041234', 'county' => 'Siaya', 'county_code' => 'KE041'),
                array('sub' => 'Awendo', 'sub_code' => 'KE044254', 'county' => 'Migori', 'county_code' => 'KE044'),
                array('sub' => 'Bahati', 'sub_code' => 'KE032174', 'county' => 'Nakuru', 'county_code' => 'KE032'),
                array('sub' => 'Balambala', 'sub_code' => 'KE007028', 'county' => 'Garissa', 'county_code' => 'KE007'),
                array('sub' => 'Banissa', 'sub_code' => 'KE009040', 'county' => 'Mandera', 'county_code' => 'KE009'),
                array('sub' => 'Baringo Central', 'sub_code' => 'KE030159', 'county' => 'Baringo', 'county_code' => 'KE030'),
                array('sub' => 'Baringo North', 'sub_code' => 'KE030158', 'county' => 'Baringo', 'county_code' => 'KE030'),
                array('sub' => 'Baringo South', 'sub_code' => 'KE030160', 'county' => 'Baringo', 'county_code' => 'KE030'),
                array('sub' => 'Belgut', 'sub_code' => 'KE035192', 'county' => 'Kericho', 'county_code' => 'KE035'),
                array('sub' => 'Bobasi', 'sub_code' => 'KE045264', 'county' => 'Kisii', 'county_code' => 'KE045'),
                array('sub' => 'Bomachoge Borabu', 'sub_code' => 'KE045263', 'county' => 'Kisii', 'county_code' => 'KE045'),
                array('sub' => 'Bomachoge Chache', 'sub_code' => 'KE045265', 'county' => 'Kisii', 'county_code' => 'KE045'),
                array('sub' => 'Bomet Central', 'sub_code' => 'KE036197', 'county' => 'Bomet', 'county_code' => 'KE036'),
                array('sub' => 'Bomet East', 'sub_code' => 'KE036196', 'county' => 'Bomet', 'county_code' => 'KE036'),
                array('sub' => 'Bonchari', 'sub_code' => 'KE045261', 'county' => 'Kisii', 'county_code' => 'KE045'),
                array('sub' => 'Bondo', 'sub_code' => 'KE041236', 'county' => 'Siaya', 'county_code' => 'KE041'),
                array('sub' => 'Borabu', 'sub_code' => 'KE046273', 'county' => 'Nyamira', 'county_code' => 'KE046'),
                array('sub' => 'Budalangi', 'sub_code' => 'KE040231', 'county' => 'Busia', 'county_code' => 'KE040'),
                array('sub' => 'Bumula', 'sub_code' => 'KE039219', 'county' => 'Bungoma', 'county_code' => 'KE039'),
                array('sub' => 'Bura', 'sub_code' => 'KE004020', 'county' => 'Tana River', 'county_code' => 'KE004'),
                array('sub' => 'Buret', 'sub_code' => 'KE035191', 'county' => 'Kericho', 'county_code' => 'KE035'),
                array('sub' => 'Butere', 'sub_code' => 'KE037207', 'county' => 'Kakamega', 'county_code' => 'KE037'),
                array('sub' => 'Butula', 'sub_code' => 'KE040229', 'county' => 'Busia', 'county_code' => 'KE040'),
                array('sub' => 'Buuri', 'sub_code' => 'KE012057', 'county' => 'Meru', 'county_code' => 'KE012'),
                array('sub' => 'Cental Imenti', 'sub_code' => 'KE012058', 'county' => 'Meru', 'county_code' => 'KE012'),
                array('sub' => 'Changamwe', 'sub_code' => 'KE001001', 'county' => 'Mombasa', 'county_code' => 'KE001'),
                array('sub' => 'Chepalungu', 'sub_code' => 'KE036195', 'county' => 'Bomet', 'county_code' => 'KE036'),
                array('sub' => 'Cherangany', 'sub_code' => 'KE026140', 'county' => 'Trans Nzoia', 'county_code' => 'KE026'),
                array('sub' => 'Chesumei', 'sub_code' => 'KE029154', 'county' => 'Nandi', 'county_code' => 'KE029'),
                array('sub' => 'Dadaab', 'sub_code' => 'KE007030', 'county' => 'Garissa', 'county_code' => 'KE007'),
                array('sub' => 'Dagoretti', 'sub_code' => 'KE047276', 'county' => 'Nairobi', 'county_code' => 'KE047'),
                array('sub' => 'Dujis', 'sub_code' => 'KE007027', 'county' => 'Garissa', 'county_code' => 'KE007'),
                array('sub' => 'Eldama Ravine', 'sub_code' => 'KE030162', 'county' => 'Baringo', 'county_code' => 'KE030'),
                array('sub' => 'Eldas', 'sub_code' => 'KE008037', 'county' => 'Wajir', 'county_code' => 'KE008'),
                array('sub' => 'Embakasi Central', 'sub_code' => 'KE047284', 'county' => 'Nairobi', 'county_code' => 'KE047'),
                array('sub' => 'Embakasi East', 'sub_code' => 'KE047285', 'county' => 'Nairobi', 'county_code' => 'KE047'),
                array('sub' => 'Embakasi North', 'sub_code' => 'KE047283', 'county' => 'Nairobi', 'county_code' => 'KE047'),
                array('sub' => 'Embakasi South', 'sub_code' => 'KE047282', 'county' => 'Nairobi', 'county_code' => 'KE047'),
                array('sub' => 'Embakasi West', 'sub_code' => 'KE047286', 'county' => 'Nairobi', 'county_code' => 'KE047'),
                array('sub' => 'Emgwen', 'sub_code' => 'KE029155', 'county' => 'Nandi', 'county_code' => 'KE029'),
                array('sub' => 'Emuhaya', 'sub_code' => 'KE038215', 'county' => 'Vihiga', 'county_code' => 'KE038'),
                array('sub' => 'Emurua Dikirr', 'sub_code' => 'KE033178', 'county' => 'Narok', 'county_code' => 'KE033'),
                array('sub' => 'Endebess', 'sub_code' => 'KE026137', 'county' => 'Trans Nzoia', 'county_code' => 'KE026'),
                array('sub' => 'Fafi', 'sub_code' => 'KE007031', 'county' => 'Garissa', 'county_code' => 'KE007'),
                array('sub' => 'Funyula', 'sub_code' => 'KE040230', 'county' => 'Busia', 'county_code' => 'KE040'),
                array('sub' => 'Gachoka', 'sub_code' => 'KE014065', 'county' => 'Embu', 'county_code' => 'KE014'),
                array('sub' => 'Galole', 'sub_code' => 'KE004019', 'county' => 'Tana River', 'county_code' => 'KE0'),
                array('sub' => 'Ganze', 'sub_code' => 'KE003015', 'county' => 'Kilifi', 'county_code' => 'KE003'),
                array('sub' => 'Garsen', 'sub_code' => 'KE004018', 'county' => 'Tana River', 'county_code' => 'KE004'),
                array('sub' => 'Gatanga', 'sub_code' => 'KE021110', 'county' => 'Murang\'a', 'county_code' => 'KE021'),
                array('sub' => 'Gatundu North', 'sub_code' => 'KE022112', 'county' => 'Kiambu', 'county_code' => 'KE022'),
                array('sub' => 'Gatundu South', 'sub_code' => 'KE022111', 'county' => 'Kiambu', 'county_code' => 'KE022'),
                array('sub' => 'Gem', 'sub_code' => 'KE041235', 'county' => 'Siaya', 'county_code' => 'KE041'),
                array('sub' => 'Gichugu', 'sub_code' => 'KE020101', 'county' => 'Kirinyaga', 'county_code' => 'KE020'),
                array('sub' => 'Gilgil', 'sub_code' => 'KE032169', 'county' => 'Nakuru', 'county_code' => 'KE032'),
                array('sub' => 'Githunguri', 'sub_code' => 'KE022116', 'county' => 'Kiambu', 'county_code' => 'KE022'),
                array('sub' => 'Hamisi', 'sub_code' => 'KE038213', 'county' => 'Vihiga', 'county_code' => 'KE038'),
                array('sub' => 'Homa Bay', 'sub_code' => 'KEsub_code043249', 'county' => 'Homa Bay', 'county_code' => 'KE043'),
                array('sub' => 'Igembe Central', 'sub_code' => 'KE012052', 'county' => 'Meru', 'county_code' => 'KE012'),
                array('sub' => 'Igembe North', 'sub_code' => 'KE012053', 'county' => 'Meru', 'county_code' => 'KE012'),
                array('sub' => 'Igembe South', 'sub_code' => 'KE012051', 'county' => 'Meru', 'county_code' => 'KE012'),
                array('sub' => 'Ijara', 'sub_code' => 'KE007032', 'county' => 'Garissa', 'county_code' => 'KE007'),
                array('sub' => 'Ikolomani', 'sub_code' => 'KE037210', 'county' => 'Kakamega', 'county_code' => 'KE037'),
                array('sub' => 'Isiolo North', 'sub_code' => 'KE011049', 'county' => 'Isiolo', 'county_code' => 'KE011'),
                array('sub' => 'Isiolo South', 'sub_code' => 'KE011050', 'county' => 'Isiolo', 'county_code' => 'KE011'),
                array('sub' => 'Jomvu', 'sub_code' => 'KE001002', 'county' => 'Mombasa', 'county_code' => 'KE001'),
                array('sub' => 'Juja', 'sub_code' => 'KE022113', 'county' => 'Kiambu', 'county_code' => 'KE022'),
                array('sub' => 'Kabete', 'sub_code' => 'KE022119', 'county' => 'Kiambu', 'county_code' => 'KE022'),
                array('sub' => 'Kabondo Kasipul', 'sub_code' => 'KE043246', 'county' => 'Homa Bay', 'county_code' => 'KE043'),
                array('sub' => 'Kabuchai', 'sub_code' => 'KE039218', 'county' => 'Bungoma', 'county_code' => 'KE039'),
                array('sub' => 'Kacheliba', 'sub_code' => 'KE024131', 'county' => 'West Pokot', 'county_code' => 'KE024'),
                array('sub' => 'Kaiti', 'sub_code' => 'KE017085', 'county' => 'Makueni', 'county_code' => 'KE017'),
                array('sub' => 'Kajiado Central', 'sub_code' => 'KE034184', 'county' => 'Kajiado', 'county_code' => 'KE034'),
                array('sub' => 'Kajiado East', 'sub_code' => 'KE034186', 'county' => 'Kajiado', 'county_code' => 'KE034'),
                array('sub' => 'Kajiado North', 'sub_code' => 'KE034183', 'county' => 'Kajiado', 'county_code' => 'KE034'),
                array('sub' => 'Kajiado South', 'sub_code' => 'KE034187', 'county' => 'Kajiado', 'county_code' => 'KE034'),
                array('sub' => 'Kajiado West', 'sub_code' => 'KE034185', 'county' => 'Kajiado', 'county_code' => 'KE034'),
                array('sub' => 'Kaloleni', 'sub_code' => 'KE003013', 'county' => 'Kilifi', 'county_code' => 'KE003'),
                array('sub' => 'Kamukunji', 'sub_code' => 'KE047288', 'county' => 'Nairobi', 'county_code' => 'KE047'),
                array('sub' => 'Kandara', 'sub_code' => 'KE021109', 'county' => 'Murang\'a', 'county_code' => 'KE021'),
                array('sub' => 'Kanduyi', 'sub_code' => 'KE039220', 'county' => 'Bungoma', 'county_code' => 'KE039'),
                array('sub' => 'Kangema', 'sub_code' => 'KE021104', 'county' => 'Murang\'a', 'county_code' => 'KE021'),
                array('sub' => 'Kangundo', 'sub_code' => 'KE016077', 'county' => 'Machakos', 'county_code' => 'KE016'),
                array('sub' => 'Kapenguria', 'sub_code' => 'KE024129', 'county' => 'West Pokot', 'county_code' => 'KE024'),
                array('sub' => 'Kapseret', 'sub_code' => 'KE027145', 'county' => 'Uasin Gishu', 'county_code' => 'KE027'),
                array('sub' => 'Karachuonyo', 'sub_code' => 'KE043247', 'county' => 'Homa Bay', 'county_code' => 'KE043'),
                array('sub' => 'Kasarani', 'sub_code' => 'KE047280', 'county' => 'Nairobi', 'county_code' => 'KE047'),
                array('sub' => 'Kasipul', 'sub_code' => 'KE043245', 'county' => 'Homa Bay', 'county_code' => 'KE043'),
                array('sub' => 'Kathiani', 'sub_code' => 'KE016079', 'county' => 'Machakos', 'county_code' => 'KE016'),
                array('sub' => 'Keiyo North', 'sub_code' => 'KE028149', 'county' => 'Elgeyo-Marakwet', 'county_code' => 'KE028'),
                array('sub' => 'Keiyo South', 'sub_code' => 'KE028150', 'county' => 'Elgeyo-Marakwet', 'county_code' => 'KE028'),
                array('sub' => 'Kesses', 'sub_code' => 'KE027146', 'county' => 'Uasin Gishu', 'county_code' => 'KE027'),
                array('sub' => 'Khwisero', 'sub_code' => 'KE037208', 'county' => 'Kakamega', 'county_code' => 'KE037'),
                array('sub' => 'Kiambaa', 'sub_code' => 'KE022118', 'county' => 'Kiambu', 'county_code' => 'KE022'),
                array('sub' => 'Kiambu', 'sub_code' => 'KE022117', 'county' => 'Kiambu', 'county_code' => 'KE022'),
                array('sub' => 'Kibra', 'sub_code' => 'KE047278', 'county' => 'Nairobi', 'county_code' => 'KE047'),
                array('sub' => 'Kibwezi East', 'sub_code' => 'KE017088', 'county' => 'Makueni', 'county_code' => 'KE017'),
                array('sub' => 'Kibwezi West', 'sub_code' => 'KE017087', 'county' => 'Makueni', 'county_code' => 'KE017'),
                array('sub' => 'Kieni', 'sub_code' => 'KE019095', 'county' => 'Nyeri', 'county_code' => 'KE019'),
                array('sub' => 'Kigumo', 'sub_code' => 'KE021107', 'county' => 'Murang\'a', 'county_code' => 'KE021'),
                array('sub' => 'Kiharu', 'sub_code' => 'KE021106', 'county' => 'Murang\'a', 'county_code' => 'KE021'),
                array('sub' => 'Kikuyu', 'sub_code' => 'KE022120', 'county' => 'Kiambu', 'county_code' => 'KE022'),
                array('sub' => 'Kilgoris', 'sub_code' => 'KE033177', 'county' => 'Narok', 'county_code' => 'KE033'),
                array('sub' => 'Kilifi North', 'sub_code' => 'KE003011', 'county' => 'Kilifi', 'county_code' => 'KE003'),
                array('sub' => 'Kilifi South', 'sub_code' => 'KE003012', 'county' => 'Kilifi', 'county_code' => 'KE003'),
                array('sub' => 'Kilimani', 'sub_code' => 'KE047275', 'county' => 'Nairobi', 'county_code' => 'KE047'),
                array('sub' => 'Kilome', 'sub_code' => 'KE017084', 'county' => 'Makueni', 'county_code' => 'KE017'),
                array('sub' => 'Kimilili', 'sub_code' => 'KE039223', 'county' => 'Bungoma', 'county_code' => 'KE039'),
                array('sub' => 'Kiminini', 'sub_code' => 'KE026139', 'county' => 'Trans Nzoia', 'county_code' => 'KE026'),
                array('sub' => 'Kinango', 'sub_code' => 'KE002010', 'county' => 'Kwale', 'county_code' => 'KE002'),
                array('sub' => 'Kinangop', 'sub_code' => 'KE018089', 'county' => 'Nyandarua', 'county_code' => 'KE018'),
                array('sub' => 'Kipipiri', 'sub_code' => 'KE018090', 'county' => 'Nyandarua', 'county_code' => 'KE018'),
                array('sub' => 'Kipkelion East', 'sub_code' => 'KE035188', 'county' => 'Kericho', 'county_code' => 'KE035'),
                array('sub' => 'Kipkelion West', 'sub_code' => 'KE035189', 'county' => 'Kericho', 'county_code' => 'KE035'),
                array('sub' => 'Kirinyaga Central', 'sub_code' => 'KE020103', 'county' => 'Kirinyaga', 'county_code' => 'KE020'),
                array('sub' => 'Kisauni', 'sub_code' => 'KE001003', 'county' => 'Mombasa', 'county_code' => 'KE001'),
                array('sub' => 'Kisumu Central', 'sub_code' => 'KE042240', 'county' => 'Kisumu', 'county_code' => 'KE042'),
                array('sub' => 'Kisumu East', 'sub_code' => 'KE042238', 'county' => 'Kisumu', 'county_code' => 'KE042'),
                array('sub' => 'Kisumu West', 'sub_code' => 'KE042239', 'county' => 'Kisumu', 'county_code' => 'KE042'),
                array('sub' => 'Kitui Central', 'sub_code' => 'KE015072', 'county' => 'Kitui', 'county_code' => 'KE015'),
                array('sub' => 'Kitui East', 'sub_code' => 'KE015073', 'county' => 'Kitui', 'county_code' => 'KE015'),
                array('sub' => 'Kitui Rural', 'sub_code' => 'KE015071', 'county' => 'Kitui', 'county_code' => 'KE015'),
                array('sub' => 'Kitui South', 'sub_code' => 'KE015074', 'county' => 'Kitui', 'county_code' => 'KE015'),
                array('sub' => 'Kitui West', 'sub_code' => 'KE015070', 'county' => 'Kitui', 'county_code' => 'KE015'),
                array('sub' => 'Kitutu Chache North', 'sub_code' => 'KE045268', 'county' => 'Kisii', 'county_code' => 'KE045'),
                array('sub' => 'Kitutu Chache South', 'sub_code' => 'KE045269', 'county' => 'Kisii', 'county_code' => 'KE045'),
                array('sub' => 'Kitutu Masaba', 'sub_code' => 'KE046270', 'county' => 'Nyamira', 'county_code' => 'KE046'),
                array('sub' => 'Konoin', 'sub_code' => 'KE036198', 'county' => 'Bomet', 'county_code' => 'KE036'),
                array('sub' => 'Kuresoi North', 'sub_code' => 'KE032171', 'county' => 'Nakuru', 'county_code' => 'KE032'),
                array('sub' => 'Kuresoi South', 'sub_code' => 'KE032170', 'county' => 'Nakuru', 'county_code' => 'KE032'),
                array('sub' => 'Kuria East', 'sub_code' => 'KE044260', 'county' => 'Migori', 'county_code' => 'KE044'),
                array('sub' => 'Kuria West', 'sub_code' => 'KE044259', 'county' => 'Migori', 'county_code' => 'KE044'),
                array('sub' => 'Kwanza', 'sub_code' => 'KE026136', 'county' => 'Trans Nzoia', 'county_code' => 'KE026'),
                array('sub' => 'Lafey', 'sub_code' => 'KE009044', 'county' => 'Mandera', 'county_code' => 'KE009'),
                array('sub' => 'Lagdera', 'sub_code' => 'KE007029', 'county' => 'Garissa', 'county_code' => 'KE007'),
                array('sub' => 'Laikipia East', 'sub_code' => 'KE031164', 'county' => 'Laikipia', 'county_code' => 'KE031'),
                array('sub' => 'Laikipia North', 'sub_code' => 'KE031165', 'county' => 'Laikipia', 'county_code' => 'KE031'),
                array('sub' => 'Laikipia West', 'sub_code' => 'KE031163', 'county' => 'Laikipia', 'county_code' => 'KE031'),
                array('sub' => 'Laisamis', 'sub_code' => 'KE010048', 'county' => 'Marsabit', 'county_code' => 'KE010'),
                array('sub' => 'Lamu East', 'sub_code' => 'KE005021', 'county' => 'Lamu', 'county_code' => 'KE005'),
                array('sub' => 'Lamu West', 'sub_code' => 'KE005022', 'county' => 'Lamu', 'county_code' => 'KE005'),
                array('sub' => 'Langata', 'sub_code' => 'KE047277', 'county' => 'Nairobi', 'county_code' => 'KE047'),
                array('sub' => 'Lari', 'sub_code' => 'KE022122', 'county' => 'Kiambu', 'county_code' => 'KE022'),
                array('sub' => 'Likoni', 'sub_code' => 'KE001005', 'county' => 'Mombasa', 'county_code' => 'KE001'),
                array('sub' => 'Likuyani', 'sub_code' => 'KE037200', 'county' => 'Kakamega', 'county_code' => 'KE037'),
                array('sub' => 'Limuru', 'sub_code' => 'KE022121', 'county' => 'Kiambu', 'county_code' => 'KE022'),
                array('sub' => 'Loima', 'sub_code' => 'KE023126', 'county' => 'Turkana', 'county_code' => 'KE023'),
                array('sub' => 'Luanda', 'sub_code' => 'KE038214', 'county' => 'Vihiga', 'county_code' => 'KE038'),
                array('sub' => 'Lugari', 'sub_code' => 'KE037199', 'county' => 'Kakamega', 'county_code' => 'KE037'),
                array('sub' => 'Lunga Lunga', 'sub_code' => 'KE002008', 'county' => 'Kwale', 'county_code' => 'KE002'),
                array('sub' => 'Lurambi', 'sub_code' => 'KE037202', 'county' => 'Kakamega', 'county_code' => 'KE037'),
                array('sub' => 'Maara', 'sub_code' => 'KE013061', 'county' => 'Tharaka-Nithi', 'county_code' => 'KE013'),
                array('sub' => 'Machakos Town', 'sub_code' => 'KE016081', 'county' => 'Machakos', 'county_code' => 'KE016'),
                array('sub' => 'Magarini', 'sub_code' => 'KE003017', 'county' => 'Kilifi', 'county_code' => 'KE003'),
                array('sub' => 'Makadara', 'sub_code' => 'KE047287', 'county' => 'Nairobi', 'county_code' => 'KE047'),
                array('sub' => 'Makueni', 'sub_code' => 'KE017086', 'county' => 'Makueni', 'county_code' => 'KE017'),
                array('sub' => 'Malava', 'sub_code' => 'KE037201', 'county' => 'Kakamega', 'county_code' => 'KE037'),
                array('sub' => 'Malindi', 'sub_code' => 'KE003016', 'county' => 'Kilifi', 'county_code' => 'KE003'),
                array('sub' => 'Mandera East', 'sub_code' => 'KE009043', 'county' => 'Mandera', 'county_code' => 'KE009'),
                array('sub' => 'Mandera North', 'sub_code' => 'KE009041', 'county' => 'Mandera', 'county_code' => 'KE009'),
                array('sub' => 'Mandera South', 'sub_code' => 'KE009042', 'county' => 'Mandera', 'county_code' => 'KE009'),
                array('sub' => 'Mandera West', 'sub_code' => 'KE009039', 'county' => 'Mandera', 'county_code' => 'KE009'),
                array('sub' => 'Manyatta', 'sub_code' => 'KE014063', 'county' => 'Embu', 'county_code' => 'KE014'),
                array('sub' => 'Maragwa', 'sub_code' => 'KE021108', 'county' => 'Murang\'a', 'county_code' => 'KE021'),
                array('sub' => 'Marakwet East', 'sub_code' => 'KE028147', 'county' => 'Elgeyo-Marakwet', 'county_code' => 'KE028'),
                array('sub' => 'Marakwet West', 'sub_code' => 'KE028148', 'county' => 'Elgeyo-Marakwet', 'county_code' => 'KE028'),
                array('sub' => 'Masinga', 'sub_code' => 'KE016075', 'county' => 'Machakos', 'county_code' => 'KE016'),
                array('sub' => 'Matayos', 'sub_code' => 'KE040228', 'county' => 'Busia', 'county_code' => 'KE040'),
                array('sub' => 'Mathare', 'sub_code' => 'KE047290', 'county' => 'Nairobi', 'county_code' => 'KE047'),
                array('sub' => 'Mathioya', 'sub_code' => 'KE021105', 'county' => 'Murang\'a', 'county_code' => 'KE021'),
                array('sub' => 'Mathira', 'sub_code' => 'KE019096', 'county' => 'Nyeri', 'county_code' => 'KE019'),
                array('sub' => 'Matuga', 'sub_code' => 'KE002009', 'county' => 'Kwale', 'county_code' => 'KE002'),
                array('sub' => 'Matungu', 'sub_code' => 'KE037206', 'county' => 'Kakamega', 'county_code' => 'KE037'),
                array('sub' => 'Matungulu', 'sub_code' => 'KE016078', 'county' => 'Machakos', 'county_code' => 'KE016'),
                array('sub' => 'Mavoko', 'sub_code' => 'KE016080', 'county' => 'Machakos', 'county_code' => 'KE016'),
                array('sub' => 'Mbooni', 'sub_code' => 'KE017083', 'county' => 'Makueni', 'county_code' => 'KE017'),
                array('sub' => 'Mogotio', 'sub_code' => 'KE030161', 'county' => 'Baringo', 'county_code' => 'KE030'),
                array('sub' => 'Moiben', 'sub_code' => 'KE027143', 'county' => 'Uasin Gishu', 'county_code' => 'KE027'),
                array('sub' => 'Molo', 'sub_code' => 'KE032166', 'county' => 'Nakuru', 'county_code' => 'KE032'),
                array('sub' => 'Mosop', 'sub_code' => 'KE029156', 'county' => 'Nandi', 'county_code' => 'KE029'),
                array('sub' => 'Moyale', 'sub_code' => 'KE010045', 'county' => 'Marsabit', 'county_code' => 'KE010'),
                array('sub' => 'Msambweni', 'sub_code' => 'KE002007', 'county' => 'Kwale', 'county_code' => 'KE002'),
                array('sub' => 'Mt. Elgon', 'sub_code' => 'KE039216', 'county' => 'Bungoma', 'county_code' => 'KE039'),
                array('sub' => 'Muhoroni', 'sub_code' => 'KE042243', 'county' => 'Kisumu', 'county_code' => 'KE042'),
                array('sub' => 'Mukurweni', 'sub_code' => 'KE019098', 'county' => 'Nyeri', 'county_code' => 'KE019'),
                array('sub' => 'Mumias East', 'sub_code' => 'KE037205', 'county' => 'Kakamega', 'county_code' => 'KE037'),
                array('sub' => 'Mumias West', 'sub_code' => 'KE037204', 'county' => 'Kakamega', 'county_code' => 'KE037'),
                array('sub' => 'Mvita', 'sub_code' => 'KE001006', 'county' => 'Mombasa', 'county_code' => 'KE001'),
                array('sub' => 'Mwala', 'sub_code' => 'KE016082', 'county' => 'Machakos', 'county_code' => 'KE016'),
                array('sub' => 'Mwatate', 'sub_code' => 'KE006025', 'county' => 'Taita Taveta', 'county_code' => 'KE006'),
                array('sub' => 'Mwea', 'sub_code' => 'KE020100', 'county' => 'Kirinyaga', 'county_code' => 'KE020'),
                array('sub' => 'Mwingi East', 'sub_code' => 'KE015069', 'county' => 'Kitui', 'county_code' => 'KE015'),
                array('sub' => 'Mwingi North', 'sub_code' => 'KE015067', 'county' => 'Kitui', 'county_code' => 'KE015'),
                array('sub' => 'Mwingi West', 'sub_code' => 'KE015068', 'county' => 'Kitui', 'county_code' => 'KE015'),
                array('sub' => 'Naivasha', 'sub_code' => 'KE032168', 'county' => 'Nakuru', 'county_code' => 'KE032'),
                array('sub' => 'Nakuru Town East', 'sub_code' => 'KE032176', 'county' => 'Nakuru', 'county_code' => 'KE032'),
                array('sub' => 'Nakuru Town West', 'sub_code' => 'KE032175', 'county' => 'Nakuru', 'county_code' => 'KE032'),
                array('sub' => 'Nambale', 'sub_code' => 'KE040227', 'county' => 'Busia', 'county_code' => 'KE040'),
                array('sub' => 'Nandi Hills', 'sub_code' => 'KE029153', 'county' => 'Nandi', 'county_code' => 'KE029'),
                array('sub' => 'Narok East', 'sub_code' => 'KE033180', 'county' => 'Narok', 'county_code' => 'KE033'),
                array('sub' => 'Narok North', 'sub_code' => 'KE033179', 'county' => 'Narok', 'county_code' => 'KE033'),
                array('sub' => 'Narok South', 'sub_code' => 'KE033181', 'county' => 'Narok', 'county_code' => 'KE033'),
                array('sub' => 'Narok West', 'sub_code' => 'KE033182', 'county' => 'Narok', 'county_code' => 'KE033'),
                array('sub' => 'Navakholo', 'sub_code' => 'KE037203', 'county' => 'Kakamega', 'county_code' => 'KE037'),
                array('sub' => 'Ndaragwa', 'sub_code' => 'KE018093', 'county' => 'Nyandarua', 'county_code' => 'KE018'),
                array('sub' => 'Ndhiwa', 'sub_code' => 'KE043250', 'county' => 'Homa Bay', 'county_code' => 'KE043'),
                array('sub' => 'Ndia', 'sub_code' => 'KE020102', 'county' => 'Kirinyaga', 'county_code' => 'KE020'),
                array('sub' => 'Nithi', 'sub_code' => 'KE013060', 'county' => 'Tharaka-Nithi', 'county_code' => 'KE013'),
                array('sub' => 'Njoro', 'sub_code' => 'KE032167', 'county' => 'Nakuru', 'county_code' => 'KE032'),
                array('sub' => 'North Horr', 'sub_code' => 'KE010046', 'county' => 'Marsabit', 'county_code' => 'KE010'),
                array('sub' => 'North Imenti', 'sub_code' => 'KE012056', 'county' => 'Meru', 'county_code' => 'KE012'),
                array('sub' => 'North Mugirango', 'sub_code' => 'KE046272', 'county' => 'Nyamira', 'county_code' => 'KE046'),
                array('sub' => 'Nyakach', 'sub_code' => 'KE042244', 'county' => 'Kisumu', 'county_code' => 'KE042'),
                array('sub' => 'Nyali', 'sub_code' => 'KE001004', 'county' => 'Mombasa', 'county_code' => 'KE001'),
                array('sub' => 'Nyando', 'sub_code' => 'KE042242', 'county' => 'Kisumu', 'county_code' => 'KE042'),
                array('sub' => 'Nyaribari Chache', 'sub_code' => 'KE045267', 'county' => 'Kisii', 'county_code' => 'KE045'),
                array('sub' => 'Nyaribari Masaba', 'sub_code' => 'KE045266', 'county' => 'Kisii', 'county_code' => 'KE045'),
                array('sub' => 'Nyatike', 'sub_code' => 'KE044258', 'county' => 'Migori', 'county_code' => 'KE044'),
                array('sub' => 'Nyeri Town', 'sub_code' => 'KE019099', 'county' => 'Nyeri', 'county_code' => 'KE019'),
                array('sub' => 'Ol Jorok', 'sub_code' => 'KE018092', 'county' => 'Nyandarua', 'county_code' => 'KE018'),
                array('sub' => 'Ol Kalou', 'sub_code' => 'KE018091', 'county' => 'Nyandarua', 'county_code' => 'KE018'),
                array('sub' => 'Othaya', 'sub_code' => 'KE019097', 'county' => 'Nyeri', 'county_code' => 'KE019'),
                array('sub' => 'Pokot South', 'sub_code' => 'KE024132', 'county' => 'West Pokot', 'county_code' => 'KE024'),
                array('sub' => 'Rabai', 'sub_code' => 'KE003014', 'county' => 'Kilifi', 'county_code' => 'KE003'),
                array('sub' => 'Rangwe', 'sub_code' => 'KE043248', 'county' => 'Homa Bay', 'county_code' => 'KE043'),
                array('sub' => 'Rarieda', 'sub_code' => 'KE041237', 'county' => 'Siaya', 'county_code' => 'KE041'),
                array('sub' => 'Rongai', 'sub_code' => 'KE032173', 'county' => 'Nakuru', 'county_code' => 'KE032'),
                array('sub' => 'Rongo', 'sub_code' => 'KE044253', 'county' => 'Migori', 'county_code' => 'KE044'),
                array('sub' => 'Roysambu', 'sub_code' => 'KE047279', 'county' => 'Nairobi', 'county_code' => 'KE047'),
                array('sub' => 'Ruaraka', 'sub_code' => 'KE047281', 'county' => 'Nairobi', 'county_code' => 'KE047'),
                array('sub' => 'Ruiru', 'sub_code' => 'KE022115', 'county' => 'Kiambu', 'county_code' => 'KE022'),
                array('sub' => 'Runyenjes', 'sub_code' => 'KE014064', 'county' => 'Embu', 'county_code' => 'KE014'),
                array('sub' => 'Sabatia', 'sub_code' => 'KE038212', 'county' => 'Vihiga', 'county_code' => 'KE038'),
                array('sub' => 'Saboti', 'sub_code' => 'KE026138', 'county' => 'Trans Nzoia', 'county_code' => 'KE026'),
                array('sub' => 'Saku', 'sub_code' => 'KE010047', 'county' => 'Marsabit', 'county_code' => 'KE010'),
                array('sub' => 'Samburu East', 'sub_code' => 'KE025135', 'county' => 'Samburu', 'county_code' => 'KE025'),
                array('sub' => 'Samburu North', 'sub_code' => 'KE025134', 'county' => 'Samburu', 'county_code' => 'KE025'),
                array('sub' => 'Samburu West', 'sub_code' => 'KE025133', 'county' => 'Samburu', 'county_code' => 'KE025'),
                array('sub' => 'Seme', 'sub_code' => 'KE042241', 'county' => 'Kisumu', 'county_code' => 'KE042'),
                array('sub' => 'Shinyalu', 'sub_code' => 'KE037209', 'county' => 'Kakamega', 'county_code' => 'KE037'),
                array('sub' => 'Siakago', 'sub_code' => 'KE014066', 'county' => 'Embu', 'county_code' => 'KE014'),
                array('sub' => 'Sigor', 'sub_code' => 'KE024130', 'county' => 'West Pokot', 'county_code' => 'KE024'),
                array('sub' => 'Sigowet/Soin', 'sub_code' => 'KE035193', 'county' => 'Kericho', 'county_code' => 'KE035'),
                array('sub' => 'Sirisia', 'sub_code' => 'KE039217', 'county' => 'Bungoma', 'county_code' => 'KE039'),
                array('sub' => 'Sotik', 'sub_code' => 'KE036194', 'county' => 'Bomet', 'county_code' => 'KE036'),
                array('sub' => 'South Imenti', 'sub_code' => 'KE012059', 'county' => 'Meru', 'county_code' => 'KE012'),
                array('sub' => 'South Mugirango', 'sub_code' => 'KE045262', 'county' => 'Kisii', 'county_code' => 'KE045'),
                array('sub' => 'Soy', 'sub_code' => 'KE027141', 'county' => 'Uasin Gishu', 'county_code' => 'KE027'),
                array('sub' => 'Starehe', 'sub_code' => 'KE047289', 'county' => 'Nairobi', 'county_code' => 'KE047'),
                array('sub' => 'Suba North', 'sub_code' => 'KE043251', 'county' => 'Homa Bay', 'county_code' => 'KE043'),
                array('sub' => 'Suba South', 'sub_code' => 'KE043252', 'county' => 'Homa Bay', 'county_code' => 'KE043'),
                array('sub' => 'Subukia', 'sub_code' => 'KE032172', 'county' => 'Nakuru', 'county_code' => 'KE032'),
                array('sub' => 'Suna East', 'sub_code' => 'KE044255', 'county' => 'Migori', 'county_code' => 'KE044'),
                array('sub' => 'Suna West', 'sub_code' => 'KE044256', 'county' => 'Migori', 'county_code' => 'KE044'),
                array('sub' => 'Tarbaj', 'sub_code' => 'KE008035', 'county' => 'Wajir', 'county_code' => 'KE008'),
                array('sub' => 'Taveta', 'sub_code' => 'KE006023', 'county' => 'Taita Taveta', 'county_code' => 'KE006'),
                array('sub' => 'Teso North', 'sub_code' => 'KE040225', 'county' => 'Busia', 'county_code' => 'KE040'),
                array('sub' => 'Teso South', 'sub_code' => 'KE040226', 'county' => 'Busia', 'county_code' => 'KE040'),
                array('sub' => 'Tetu', 'sub_code' => 'KE019094', 'county' => 'Nyeri', 'county_code' => 'KE019'),
                array('sub' => 'Tharaka', 'sub_code' => 'KE013062', 'county' => 'Tharaka-Nithi', 'county_code' => 'KE013'),
                array('sub' => 'Thika Town', 'sub_code' => 'KE022114', 'county' => 'Kiambu', 'county_code' => 'KE022'),
                array('sub' => 'Tiaty', 'sub_code' => 'KE030157', 'county' => 'Baringo', 'county_code' => 'KE030'),
                array('sub' => 'Tigania East', 'sub_code' => 'KE012055', 'county' => 'Meru', 'county_code' => 'KE012'),
                array('sub' => 'Tigania West', 'sub_code' => 'KE012054', 'county' => 'Meru', 'county_code' => 'KE012'),
                array('sub' => 'Tinderet', 'sub_code' => 'KE029151', 'county' => 'Nandi', 'county_code' => 'KE029'),
                array('sub' => 'Tongaren', 'sub_code' => 'KE039224', 'county' => 'Bungoma', 'county_code' => 'KE039'),
                array('sub' => 'Turbo', 'sub_code' => 'KE027142', 'county' => 'Uasin Gishu', 'county_code' => 'KE027'),
                array('sub' => 'Turkana Central', 'sub_code' => 'KE023125', 'county' => 'Turkana', 'county_code' => 'KE023'),
                array('sub' => 'Turkana East', 'sub_code' => 'KE023128', 'county' => 'Turkana', 'county_code' => 'KE023'),
                array('sub' => 'Turkana North', 'sub_code' => 'KE023123', 'county' => 'Turkana', 'county_code' => 'KE023'),
                array('sub' => 'Turkana South', 'sub_code' => 'KE023127', 'county' => 'Turkana', 'county_code' => 'KE023'),
                array('sub' => 'Turkana West', 'sub_code' => 'KE023124', 'county' => 'Turkana', 'county_code' => 'KE023'),
                array('sub' => 'Ugenya', 'sub_code' => 'KE041232', 'county' => 'Siaya', 'county_code' => 'KE041'),
                array('sub' => 'Ugunja', 'sub_code' => 'KE041233', 'county' => 'Siaya', 'county_code' => 'KE041'),
                array('sub' => 'Uriri', 'sub_code' => 'KE044257', 'county' => 'Migori', 'county_code' => 'KE044'),
                array('sub' => 'Vihiga', 'sub_code' => 'KE038211', 'county' => 'Vihiga', 'county_code' => 'KE038'),
                array('sub' => 'Voi', 'sub_code' => 'KE006026', 'county' => 'Taita Taveta', 'county_code' => 'KE006'),
                array('sub' => 'Wajir East', 'sub_code' => 'KE008034', 'county' => 'Wajir', 'county_code' => 'KE008'),
                array('sub' => 'Wajir North', 'sub_code' => 'KE008033', 'county' => 'Wajir', 'county_code' => 'KE008'),
                array('sub' => 'Wajir South', 'sub_code' => 'KE008038', 'county' => 'Wajir', 'county_code' => 'KE008'),
                array('sub' => 'Wajir West', 'sub_code' => 'KE008036', 'county' => 'Wajir', 'county_code' => 'KE008'),
                array('sub' => 'Webuye East', 'sub_code' => 'KE039221', 'county' => 'Bungoma', 'county_code' => 'KE039'),
                array('sub' => 'Webuye West', 'sub_code' => 'KE039222', 'county' => 'Bungoma', 'county_code' => 'KE039'),
                array('sub' => 'West Mugirango', 'sub_code' => 'KE046271', 'county' => 'Nyamira', 'county_code' => 'KE046'),
                array('sub' => 'Westlands', 'sub_code' => 'KE047274', 'county' => 'Nairobi', 'county_code' => 'KE047'),
                array('sub' => 'Wundanyi', 'sub_code' => 'KE006024', 'county' => 'Taita Taveta', 'county_code' => 'KE006'),
                array('sub' => 'Yatta', 'sub_code' => 'KE016076', 'county' => 'Machakos', 'county_code' => 'KE016'),
            )
        );
    }
}
